### ISSUE TITLE
As a user, I'd like to see an error indicator when a card image doesn't load so I can see that something is missing

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#494]
## notes for testing
Test with [Bertraud-Fontaine cards](https://test-shakespeareandco.cdh.princeton.edu/members/bertraud-fontaine/cards/), which I have broken on the test site.
- Check both the card list and card image viewer
- Check on all screen sizes

--- 

**Describe the bug**
Right now if the manifest on a card is not updated or is broken, there's not error message - the card image simply does not appear, although the dates the card has DO. 

**To reproduce**
1. Go to Bertraud-Fontaine individual member page
2. Click on CARDS
3. See that "1938" is currently floating in space with no card image

**Expected behavior**
Would like some filler text or image explaining an error loading the card image 

**Screenshots**
![Screen Shot 2019-12-13 at 4 00 21 PM](https://user-images.githubusercontent.com/16673934/70831933-d81e9d00-1dc1-11ea-9029-c8f5797dd987.png)

**Device information**
 - Device: MacBook Air
 - OS and version: OS10
 - Browser and version: Chrome
 - Site version 0.24.0

**Comment by rlskoeser** [comment]
@gissoo did you ever add the image you created in #548 to the repository? I'm not finding it.

**Comment by gissoo** [comment]
@rlskoeser Oh noo!! Should it be an svg? Or png?

**Comment by rlskoeser** [comment]
@gissoo I think SVG would make sense

**Comment by gissoo** [comment]
@rlskoeser Just added it! – Made minimal adjustments to the card sizes based on how they are calculated on the site right now.

**Comment by rlskoeser** [comment]
I have manually broken the image url for one of the Bertraud Fontaine cards on the test site so we can review this, since the problem was fixed. 
https://test-shakespeareandco.cdh.princeton.edu/members/bertraud-fontaine/cards/

@gissoo do you want to review this first?

**Comment by clmahoney** [comment]
- YES, I see this card error image: 
![Screen Shot 2020-05-12 at 6 46 16 PM](https://user-images.githubusercontent.com/16673934/81753067-faa40780-9480-11ea-99b9-a42f4fe3900f.png)

Should I close or should @gissoo review?

**Comment by clmahoney** [comment]
- YES, I still see the error image when I click on it and get a bigger view: 
![Screen Shot 2020-05-12 at 7 02 36 PM](https://user-images.githubusercontent.com/16673934/81754070-3d66df00-9483-11ea-89d3-b1807f92f788.png)

**Comment by clmahoney** [comment]
Mobile: 
- YES, I see the error image when I'm on the broken link card display page: 
![IMG_2087](https://user-images.githubusercontent.com/16673934/81754298-d72e8c00-9483-11ea-9e6c-9c2de134a155.PNG)

- NO, I do NOT see that same error image when I click on the card for a closeup:
![IMG_2088](https://user-images.githubusercontent.com/16673934/81754306-dbf34000-9483-11ea-87f1-a7b0fc4d5d48.PNG)

**Comment by clmahoney** [comment]
Tablet:
- YES, I see the card image error on the card display
- YES, I also see the card image error when I click on the individual broken card

**Comment by rlskoeser** [comment]
@clmahoney thanks for the careful testing and catching this — what mobile device were you using that showed this problem?

**Comment by rlskoeser** [comment]
I've updated the test site with changes to address Firefox and mobile display issues.

**Comment by clmahoney** [comment]
@rlskoeser I was using my iPhone 6s! I'll check this again now.

**Comment by clmahoney** [comment]
Mobile: 
- YES, I see the card image error on the card display, HOWEVER: it seems to not be aligned with the other working card image: ![IMG_2101](https://user-images.githubusercontent.com/16673934/81862187-503aeb80-9537-11ea-8eb0-bf0c5d09b8a4.PNG)
- YES, I see the card image error when I click on it to see it bigger

**Comment by gissoo** [comment]
@rlskoeser These are what I see right now. 
- The link looks broken on safari and chrome. 
- The position looks right everywhere, except as Cate has mentioned, for me also specifically on the mobile gallery view on firefox and safari. 
- On the card image viewer page in mobile view the arrows don't look horizontally centered with the card, they look like they are futher down than they are supposed to be, is this an optical illusion? Or does the arrow placement actually change from desktop to mobile? I think when I expand and shrink the window on desktop it looks like it changes but I may be wrong.
- (Also, side note, why does the breadcrumb on the card image viewer page on iOS look like this? Does it have to do with truncating the name?) :(

Desktop (left-right: Firefox, Chrome, Safari)
<img width="1341" alt="Desktop – all browsers-P1" src="https://user-images.githubusercontent.com/44615389/81867835-546b0700-953f-11ea-9208-a63ca4a4e50f.png">
<img width="1341" alt="Desktop – all browsers-P2" src="https://user-images.githubusercontent.com/44615389/81867325-82038080-953e-11ea-9377-939d4f4efaea.png">

iOS Firefox
![ iOS Firefox-p1](https://user-images.githubusercontent.com/44615389/81867340-87f96180-953e-11ea-8d83-1def96c68a9e.png)
![ iOS Firefox-p2](https://user-images.githubusercontent.com/44615389/81867350-8cbe1580-953e-11ea-9ab7-2d4dac3ca93b.png)

iOS Chrome
![ iOS Chrome-p1](https://user-images.githubusercontent.com/44615389/81867363-934c8d00-953e-11ea-9e97-42ece3f56ec4.png)
![ iOS Chrome-p2](https://user-images.githubusercontent.com/44615389/81867372-96477d80-953e-11ea-82aa-43cc4139b32b.png)

iOS Safari
![ iOS Safari-p1](https://user-images.githubusercontent.com/44615389/81868470-67caa200-9540-11ea-8699-9d446a1384a3.png)
![ iOS Safari-p2](https://user-images.githubusercontent.com/44615389/81868476-6ac59280-9540-11ea-8b12-0ba42bd720d0.png)

**Comment by rlskoeser** [comment]
I updated with a fix for the offset missing image in the card list view on Safari mobile and also adjusted the vertical alignment of the next/previous arrows (@gissoo I think you were right, they did look slightly off!).

Not sure what is going on with the breadcrumb, but we should probably create a separate issue for that.

@gissoo the broken image indicators on Safari and Chrome are browser specific, and as far as I can tell there isn't an easy way to suppress them (I did some looking yesterday). @thatbudakguy do you know of anything easy here?

@gissoo do you want to re-review and close?

**Comment by clmahoney** [comment]
@gissoo @rlskoeser This looks good on my mobile view now!
